### ISSUE TITLE
Delay_func in transducer loss

### ISSUE THREAD

**Issue by Renaissance25** [danliu2/caat#4]
There is three type of delay_func，“zero”, "diagonal", "diag_positive".
Which one is corresponding to the delay loss in paper?
And what's their difference? 
It confuses me.

**Comment by danliu2** [comment]
They differ in the definition of ideal delay, where 'zero' means ideal delay is zero and 'diag*' means diagonal (wait-0） as ideal. In our paper we used 'diag_positive' only, which means a punishment if the latency is higher than wait-0 but no additional reward if the latency is lower than wait-0.

**Comment by Renaissance25** [comment]
Thanks. It helps me a lot.
