### ISSUE TITLE
Preprocessing Errors

### ISSUE THREAD

**Issue by sarapapi** [danliu2/caat#5]
Dear authors,
I tried to run your preprocessing code (a small note, in preprocess_mustc.sh there is an additional "$" before DATA_DIR that is not correct) but I run in this error:
```Traceback (most recent call last):
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/scripts/audio_process.py", line 195, in <module>
    main()
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/scripts/audio_process.py", line 192, in main
    process(indir, args.output_dir,src_lang=args.src_lang, tgt_lang=args.tgt_lang, split= data, count_mvn=count_mvn)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/scripts/audio_process.py", line 103, in process
    wav,samp_rate= audio_encoder._load_wav(wave_path, start_sec, duration_sec)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/rain/data/transforms/audio_encoder.py", line 26, in _load_wav
    sample_rate= torchaudio.info(wave_path)[0].rate
TypeError: 'AudioMetaData' object is not subscriptable
```
I think that it is maybe related to the torchaudio version, could you please tell me which torch, torchvision and torchaudio versions have you used?

In addition, I would like to know which are the files contained in the output directory at the end of the preprocessing phase, to make sure that all is working properly. I noticed that the speech to text task is a little bit different than the standard Fairseq s2t task and it would be nice if I can reuse the filterbank, the vocabulary, etc. that I already have. Is it possible to start a CAAT training with the files I already have? Have I to write some config files to make it work?

Thank you

**Comment by danliu2** [comment]
My experiments were carried with pytorch 1.7.0, torchaudio 0.7.0 and torchvision 0.8.1. Maybe structure of the return of torchaudio.info has changed, but I think you can get sample_rate from the new AudioMetaData by small modify.

I didn't start my experiment with Fairseq S2T,  so I don't know the details of their data. But I think you can use their data directly by switching __getitem__ in rain.data.audio_dataset.FBankZipDataset to their implementation. In my implementation, the data required are:
1. directory audio_cfg: the npy file for whiten and config about specaugment
2. directory text_cfg: sentence piece model , vocab file (in fairseq format), 
3.  fbank_{split}.zip: uncompressed zip file with filterbanks
4. {split}.{src}-{tgt}.{src}: source transcription
5. {split}.{src}-{tgt}.{tgt}: target translation reference
6. {split}.{src}-{tgt}.audio.tsv: audio sample list, contains position and length in fbank_{split}.zip, frames number and speaker ID.

**Comment by sarapapi** [comment]
Thanks for your answer!
